---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audience-manager-ui
  namespace: audience-manager-demo
  labels:
    app: audience-manager-ui
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audience-manager-ui
  template:
    metadata:
      labels:
        app: audience-manager-ui
        component: frontend
    spec:
      containers:
      - name: audience-manager-ui
        image: audience-manager-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "http://localhost:30180/api/v1"
        - name: REACT_APP_VERSION
          value: "1.0.0"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: audience-manager-ui-nginx-config
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: audience-manager-ui-service
  namespace: audience-manager-demo
  labels:
    app: audience-manager-ui
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30280
    name: http
  selector:
    app: audience-manager-ui

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: audience-manager-ui-nginx-config
  namespace: audience-manager-demo
  labels:
    app: audience-manager-ui
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        # Enable gzip compression
        gzip on;
        gzip_vary on;
        gzip_types
            text/plain
            text/css
            text/xml
            text/javascript
            application/javascript
            application/xml+rss
            application/json;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
        add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;

        # Handle React Router
        location / {
            try_files $uri $uri/ /index.html;
            
            # Cache static assets
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
            }
        }

        # API proxy to backend (optional - for development)
        location /api/ {
            proxy_pass http://audience-manager-api-service:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Health check endpoint
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }

        # Error pages
        error_page 404 /index.html;
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: audience-manager-ui-env-config
  namespace: audience-manager-demo
  labels:
    app: audience-manager-ui
data:
  env.js: |
    window.env = {
      REACT_APP_API_URL: "http://localhost:30180/api/v1",
      REACT_APP_VERSION: "1.0.0"
    };